server:
  port: 8081

spring:
  application:
    name: flight-service


  datasource:
    url: jdbc:mysql://localhost:3306/flight_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 0767092851
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  host: http://localhost:8081
